// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGNwPRImdBdkOhsBH1sYKF9_V41-mvuIY',
    appId: '1:733305344132:web:98b5b566430d645645b2d1',
    messagingSenderId: '733305344132',
    projectId: 'flutter-demo-246b7',
    authDomain: 'flutter-demo-246b7.firebaseapp.com',
    storageBucket: 'flutter-demo-246b7.firebasestorage.app',
    measurementId: 'G-BBQZKEWD13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD348NTjXsYrZbpy8P3QIaPw9_Txl26tOk',
    appId: '1:733305344132:android:a3b0fa9dded1ab8b45b2d1',
    messagingSenderId: '733305344132',
    projectId: 'flutter-demo-246b7',
    storageBucket: 'flutter-demo-246b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJJC4WrisdXjYU5MX2IJzAonImiGK6Ko',
    appId: '1:733305344132:ios:f18e780d54dcf70d45b2d1',
    messagingSenderId: '733305344132',
    projectId: 'flutter-demo-246b7',
    storageBucket: 'flutter-demo-246b7.firebasestorage.app',
    iosBundleId: 'com.example.memeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiJJC4WrisdXjYU5MX2IJzAonImiGK6Ko',
    appId: '1:733305344132:ios:f18e780d54dcf70d45b2d1',
    messagingSenderId: '733305344132',
    projectId: 'flutter-demo-246b7',
    storageBucket: 'flutter-demo-246b7.firebasestorage.app',
    iosBundleId: 'com.example.memeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGNwPRImdBdkOhsBH1sYKF9_V41-mvuIY',
    appId: '1:733305344132:web:a17e99ab5b58151845b2d1',
    messagingSenderId: '733305344132',
    projectId: 'flutter-demo-246b7',
    authDomain: 'flutter-demo-246b7.firebaseapp.com',
    storageBucket: 'flutter-demo-246b7.firebasestorage.app',
    measurementId: 'G-5JP1GSX78G',
  );
}
